server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: social-media-site

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

# debug: true
spring.devtools.restart.enabled: true
